MAP_WIDTH = 60.0  # [m]
MAP_HEIGHT = 60.0  # [m]
MAP_STEP = 1.0  # [m]
MAP_NUM_RANDOM_OBSTACLES = 40

GLOBAL_PLANNER_SEGMENT_COLLECTION_SIZE = 50

MOTION_RESOLUTION = 0.5  # [m] path interpolate resolution

SIMULATION_DELTA_TIME = 0.015  # [s]
SIMULATION_INTERVAL = 0.02  # [s]
SIMULATION_PUBLISH_INTERVAL = 0.05  # [s]
LOCAL_PLANNER_UPDATE_INTERVAL = 0.1  # [s]
REPLAN_MAX_SPEED = 5 / 3.6  # [m/s] - Maximum speed for replanning

LOCAL_PLANNER_DELTA_TIME = 0.07  # [s]
