MEASURED_STATE = 'measured_state'
MAP_INITIALIZED = 'map_initialized'
KNOWN_OBSTACLES_UPDATED = 'known_obstacles_updated'
NEW_OBSTACLES_DISCOVERED = 'new_obstacles_discovered'
GLOBAL_PLANNER_DISPLAY_SEGMENTS = 'global_planner_display_segments'
GLOBAL_PLANNER_TRAJECTORY = 'global_planner_trajectory'
GLOBAL_PLANNER_FINISHED = 'global_planner_finished'